n_epochs: 10

model:
  _target_: heat.ebm.HybridEnergyModel
  hidden_dim: 1024
  n_hidden_layers: 6
  temperature: 1e0
  temperature_prior: 5e3
  proposal_type: base_dist_temp
  use_base_dist: True
  sample_from_batch_statistics: True
  steps: 0
  step_size_start: 1e-7
  step_size_end: ${mult:${ebm.model.step_size_start},0.1}
  eps_start: 1e-4
  eps_end: ${mult:${ebm.model.eps_start},0.1}
  sgld_relu: True
  use_sgld: True
  use_svgd: False
  use_spectral_norm: False
  use_pcd: False
  restart_prob: 0.1
  buffer_size: 40000
  reduce_width: True
  base_dist:
    _target_: heat.scorers.SSDScorer
    num_classes: ${ifisnone:${dataset.subset.number_labels}, 1000}
    d: ${backbone.dim}
    layer_name: 'layer4'
    features_dataset: ${dataset.features_dataset}
    cache_base_dist: False
    force_fit_base_dist: True
    diag_coefficient_only: False
    pooling: ${pooling}
    use_simplified_mahalanobis_score: True
    normalize: ${normalize}
    input_preprocessing: False
    use_pca: ${use_pca}
    pca_n_principal_components: ${pca_n_principal_components}
    pca_n_last_components: ${pca_n_last_components}
    pca_whiten: ${pca_whiten}
    max_fit_iter: 1000

loss:
  _target_: heat.ebm.ContrastiveDivergenceLoss
  l2_coef: 20.
  eps_data: 1e-4
  verbose: True

optimizer:
  opt:
    _target_: torch.optim.Adam
    lr: 1e-4
    betas: [0, 0.999]

  sch:
    _target_: torch.optim.lr_scheduler.MultiStepLR
    milestones: [1]
    gamma: 0.1
